name: first_time
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  http: ^1.4.0
  shared_preferences: ^2.5.3
  scroll_to_index: ^3.0.1
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: LPMQIsepMisbah
      fonts:
        - asset: fonts/LPMQIsepMisbah.ttf
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/quran.png"